### ISSUE TITLE
Crash when selecting an image from gallery

### ISSUE THREAD

**Issue by xDualBladerZ** [mitchtabian/ForSale#2]
Hey Mitch, 

Really thankful for the code, but could you help me to solve this problem?

I am now at the part where I had done the postFragment so that I can select the photo from my gallery and camera, the camera function is working, but when I choose the photo from the gallery, the app crashes, do you know why? 

Here are the some of the logs

`D/SelectPhotoDialog: onActivityResult: image uri: content://com.android.providers.media.documents/document/image%3A77 D/UploadFragment: getImagePath: setting the image to imageview D/AndroidRuntime: Shutting down VM E/AndroidRuntime: FATAL EXCEPTION: main Process: com.fyp.elvis.recapp, PID: 3151 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=66770, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:77 flg=0x1 }} to activity {com.fyp.elvis.recapp/com.fyp.elvis.recapp.HomeActivity}: java.lang.IllegalStateException: ImageLoader must be init with configuration before using at android.app.ActivityThread.deliverResults(ActivityThread.java:4089) at android.app.ActivityThread.handleSendResult(ActivityThread.java:4132) at android.app.ActivityThread.-wrap20(ActivityThread.java) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1533) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6119) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) Caused by: java.lang.IllegalStateException: ImageLoader must be init with configuration before using at com.nostra13.universalimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:613) at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:236) at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:209) at com.nostra13.universalimageloader.core.ImageLoader.displayImage(ImageLoader.java:316) at com.fyp.elvis.recapp.util.UniversalImageLoader.setImage(UniversalImageLoader.java:46) at com.fyp.elvis.recapp.UploadFragment.getImagePath(UploadFragment.java:31) at com.fyp.elvis.recapp.SelectPhotoDialog.onActivityResult(SelectPhotoDialog.java:68) at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:151) at android.app.Activity.dispatchActivityResult(Activity.java:6932) at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)`

**Comment by xDualBladerZ** [comment]
Solved it by adding init for universalimageloader, sorry for the trouble.
